url: 'http://localhost:8082'

mongodb:
  server: REPLACE_WITH_MONGO_ENDPOINT   # localhost
  database: REPLACE_WITH_MONGO_DATABASE # uptime
  user: REPLACE_WITH_MONGO_USER
  password: REPLACE_WITH_MONGO_PWD
  connectionString:       # alternative to setting server, database, user and password separately

monitor:
  name:                   origin
  apiUrl:                 'http://localhost:8082/api' # must be accessible without a proxy
  pollingInterval:        10000      # ten seconds
  timeout:                5000       # five seconds
  userAgent:              NodeUptime/3.0 (https://github.com/springerpe/uptime)

ssl:
  enabled:                false
  certificate:            uptime.crt # certificate file
  key:                    uptime.key # key file
  selfSigned:             false

analyzer:
  updateInterval:         60000      # one minute
  qosAggregationInterval: 600000     # ten minutes
  pingHistory:            8035200000 # three months

autoStartMonitor: true

plugins:
  - ./plugins/console
  - ./plugins/patternMatcher
  - ./plugins/httpOptions
  - ./plugins/httpsOAuthOptions
  # - ./plugins/pagerduty
  # - ./plugins/email
  # - ./plugins/basicAuth
  - ./plugins/hipchat
  - ./plugins/victorops
  # - ./plugins/statushub
  - ./plugins/statuspage
  - ./plugins/httpriemann

hipchat:
  apiKey: REPLACE_WITH_HIPCHAT_APIKEY # HipChat Admin API Key https://www.hipchat.com/admin/api
  tag:
    hipchat: REPLACE_WITH_HIPCHAT_ROOM  # tag name : HipChat room ID where send notification

victorops:
  endpoint: REPLACE_WITH_VICTOROPS_ENDPOINT

#statushub:
#  endpoint: https://statushub.io/api/status_pages #the same for all
#  subdomains: REPLACE_WITH_STATUSHUB_SUBDOMAINS # for example ["my_stuff"] as you can have a number of different status pages
#  apiKey: REPLACE_WITH_STATUSHUB_APIKEY

httpriemann:
  endpoint: http://localhost:4567
  username: uptime
  password: bre9zel

pushbullet:
  apikey: ""

pagerduty:
  serviceKey: 1c1046e9fddd4d45a0302ec379144fc9
  event:
    up:        true
    down:      true
    paused:    false
    restarted: false

email:
  method:      SMTP  # possible methods are SMTP, SES, or Sendmail
  transport:         # see https://github.com/andris9/nodemailer for transport options
    service:   Gmail # see https://github.com/andris9/Nodemailer/blob/master/lib/wellknown.js for well-known services
    auth:
      user:          # The email account username, e.g. 'username@gmail.com'
      pass:          # The email account password, e.G. 'password'
  event:
    up:        true
    down:      true
    paused:    false
    restarted: false
  message:
    from:            # The message sender, e.g. 'Fred Foo <foo@blurdybloop.com>'
    to:              # The message recipient, e.g. 'bar@blurdybloop.com, baz@blurdybloop.com'
  # The email plugin also uses the main `url` param for hyperlinks in the sent emails

basicAuth:
  username:    admin
  password:    password
verbose: true # only used in dev

webPageTest:
  server: 'http://www.webpagetest.org'
  key:
  testOptions:
